services:
  backend:
    build:
      context: ./backend
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    volumes:
      - ./backend:/app
      - /app/node_modules # Исключение node_modules из монтирования
    environment:
      - NODE_ENV=development
      - BACKEND_PORT=${BACKEND_PORT}
      - MONGO_URI=${MONGO_URI}
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
      - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}
      - CHOKIDAR_USEPOLLING=true
    command: npm run dev # Используем nodemon для hot-reload
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./frontend
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    volumes:
      - ./frontend:/app
      - /app/node_modules # Исключение node_modules из монтирования
    environment:
      - NODE_ENV=development
      - FRONTEND_PORT=${FRONTEND_PORT}
      - BACKEND_PORT=${BACKEND_PORT}
      - CHOKIDAR_USEPOLLING=true
    command: npm run dev # Используем vite для hot-reload

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
